### ISSUE TITLE
Add Start date for yearly calculations

### ISSUE THREAD

**Issue by louisnorthmore** [Fishbowler/tempoflex-chrome-extension#2]
I started in February. Be nice to add a start date field to cater for this offset.

**Comment by Fishbowler** [comment]
Awesome idea! Tracking time from Jan 1st was definitely a compromise. 

Complexity will definitely be in counting working days between 1st of a period and the chosen date.
I had published https://www.npmjs.com/package/workingday-uk to support this extension, but it won't (yet) help to this extent.

**Comment by Fishbowler** [comment]
@louisnorthmore I had a great idea that I could fetch User Schedules (see #16) to solve this problem. Unfortunately, that contains the same data as Periods as regards the time you should have worked.

Likely there's a way to get this data fixed on a person-by-person basis by a Tempo admin, but a config option is definitely preferable.
