### ISSUE TITLE
Firefox compatibility

### ISSUE THREAD

**Issue by Fishbowler** [Fishbowler/tempoflex-chrome-extension#84]

**Comment by Fishbowler** [comment]
Started in `firefox_compat` branch

**Comment by grahamsmith** [comment]
![Uploading Screenshot 2020-10-06 at 09.46.42.png…]()

**Comment by grahamsmith** [comment]
![Screenshot 2020-10-06 at 09 46 42](https://user-images.githubusercontent.com/1571527/95179874-22da2d00-07b9-11eb-9f45-c4585147417f.png)

**Comment by grahamsmith** [comment]
Will add the build steps to build a Firefox build as well.

**Comment by Fishbowler** [comment]
Fixed in #183
